% Read only candidates found inside initially unconfirmed containers.
addpath('/home/charvin-admin');
inspect_sauvegarde_project_headers( ...
    '/home/charvin-admin/sauve-extra-discovery-20261001.json', ...
    '/home/charvin-admin/sauve-extra-headers-20261001.json', ...
    '/home/charvin-admin/repos/DetecDiv', ...
    '/mnt/detecdiv-secondary-sauvegarde');
