% One-shot read-only header audit on the storage-visible compute host.
addpath('/home/charvin-admin');
inspect_sauvegarde_project_headers( ...
    '/home/charvin-admin/sauvegarde-project-discovery-20261001.json', ...
    '/home/charvin-admin/sauvegarde-project-headers-20261001.json', ...
    '/home/charvin-admin/repos/DetecDiv', ...
    '/mnt/detecdiv-secondary-sauvegarde');
